-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "topBarText" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "footerAbout" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "footerOrgName" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "footerRights" JSONB NOT NULL DEFAULT '{}';
